### ISSUE TITLE
Chem Heating Bug

### ISSUE THREAD

**Issue by prawn04** [DesertRose2/desertrose#199] opened 2021-03-19 23:14 UTC

**Comment by nokele** [comment] 2021-03-23 15:11
```
/datum/chemical_reaction/reagent_explosion/methsplosion
	name = "Meth explosion"
	id = "methboom1"
	required_temp = 380 //slightly above the meth mix time.
	required_reagents = list(/datum/reagent/drug/methamphetamine = 1)
	strengthdiv = 6
	modifier = 1
	mob_react = FALSE
```
Looks intentional?

**Comment by Pebblesthe2nd** [comment] 2021-03-26 13:22
Tested this, could not reproduce, seems the issue is incorrect. Reaction temp is 374, explosion at 380 just as it should be.
Ghetto heating for meth is obviously not recommended, need to be precise.
Recommend closing issue.

**Closed** 2021-04-01 19:42 UTC
